train:
  # Run name for the training session.
  run_name: fruitdetection1
  # Directory in which model checkpoints & summaries (for Tensorboard) will be saved.
  job_dir: jobs/
  num_epochs: 30000
  learning_rate:
    decay_method: piecewise_constant
    # Custom dataset for Luminoth Tutorial
    boundaries: [9000, 16000, 25000]
    values: [0.0003, 0.0001, 0.00003, 0.00001]

dataset:
  type: object_detection
  # From which directory to read the dataset.
  dir: .
  split: train
  data_augmentation:
    - flip:
        left_right: True
        up_down: False
        prob: 0.5

model:
  type: fasterrcnn
  network:
    # Total number of classes to predict.
    num_classes: 7
  anchors:
    # Base size to use for anchors.
    base_size: 128
    # Scale used for generating anchor sizes.
    scales: [0.25, 0.5, 1, 2]
    # Aspect ratios used for generating anchors.
    ratios: [0.5, 1, 2]
    # Stride depending on feature map size (of pretrained).
    stride: 16